IF OBJECT_ID('YH_OrderStatus') IS NOT NULL
BEGIN
	DROP TABLE YH_OrderStatus
END
GO

CREATE TABLE YH_OrderStatus (
	Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	Guid UNIQUEIDENTIFIER DEFAULT NEWID(),
	Status VARCHAR(50) NOT NULL,
	CreatedDt DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedDt DATETIME NULL
);

INSERT INTO YH_OrderStatus (Status)
SELECT 'TODO'
UNION ALL
SELECT 'PAYMENT_AUTHORIZED'
UNION ALL
SELECT 'PAYMENT_CAPTURED'
UNION ALL
SELECT 'PAYMENT_FAILED'
UNION ALL
SELECT 'REFUND_CREATED'
UNION ALL
SELECT 'REFUND_PROCESSED'
UNION ALL
SELECT 'REFUND_FAILED'
UNION ALL
SELECT 'UNKNOWN'

IF OBJECT_ID('YH_Orders') IS NOT NULL
BEGIN
	DROP TABLE YH_Orders
END
GO

CREATE TABLE YH_Orders (
	Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	Guid UNIQUEIDENTIFIER DEFAULT NEWID(),
	TotalPrice NUMERIC(18,2) NOT NULL,
	CreatedDt DATETIME NOT NULL DEFAULT GETDATE(),
	StatusId_FK INT NOT NULL FOREIGN KEY REFERENCES YH_OrderStatus(Id),
	RazorOrderId VARCHAR(150) NULL,
	ModifiedDt DATETIME NULL
);

