IF OBJECT_ID('YH_OrderStatus') IS NOT NULL
BEGIN
	DROP TABLE YH_Orders
END
GO

CREATE TABLE YH_OrderStatus (
	Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	Guid UNIQUEIDENTIFIER DEFAULT NEWID(),
	Status VARCHAR(50) NOT NULL,
	CreatedDt DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedDt DATETIME NULL
);

IF OBJECT_ID('YH_Orders') IS NOT NULL
BEGIN
	DROP TABLE YH_Orders
END
GO

CREATE TABLE YH_Orders (
	Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	Guid UNIQUEIDENTIFIER DEFAULT NEWID(),
	TotalPrice NUMERIC(18,2) NOT NULL,
	CreatedDt DATETIME NOT NULL DEFAULT GETDATE(),
	StatusId_FK INT NOT NULL FOREIGN KEY REFERENCES YH_OrderStatus(Id),
	RazorPaymentId VARCHAR(150) NULL,
	RazorOrderId VARCHAR(150) NULL,
	ModifiedDt DATETIME NULL
);

