IF OBJECT_ID('YH_OrderItem') IS NOT NULL
BEGIN
	DROP TABLE YH_OrderItem
END
GO

CREATE TABLE YH_OrderItem (
	Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	Guid UNIQUEIDENTIFIER DEFAULT NEWID(),
	OrderId_FK INT NOT NULL FOREIGN KEY REFERENCES YH_Orders(Id),
	ItemPrice NUMERIC(18,2) NOT NULL,
	ItemDiscountedPrice NUMERIC(18,2) NOT NULL,
	ItemDiscount INT NULL,
	TotalPrice NUMERIC(18,2) NOT NULL,
	Quantity INT NOT NULL,
	ProductVariantId_FK INT NOT NULL FOREIGN KEY REFERENCES YH_ProductVariants(Id),
	DiscountId INT NULL FOREIGN KEY REFERENCES YH_DiscountMaster(Id),
	CreatedDt DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedDt DATETIME NULL
);