"use client"
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Providers } from '@/redux/provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import WhatsappContainer from '@/components/WhatsappContainer'
import 'react-loading-skeleton/dist/skeleton.css'
import { createTheme } from '@mui/material/styles'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} w-full bg-white relative h-full`}>
        <Providers>
          <div className='fixed bottom-5 bg-white rounded-lg z-50 right-5 m-auto flex items-center'>
            <WhatsappContainer />
          </div>
          <Header />
          {children}
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  )
}
