CREATE TABLE Customer
(
	id INT IDENTITY(1,1),
	guid UNIQUEIDENTIFIER DEFAULT NEWID(),
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NULL,
	email VARCHAR(150) NULL,
	mobile_number VARCHAR(10) NOT NULL,
	created_date DATETIME DEFAULT GETUTCDATE(),
	updated_date DATETIME NULL,
	PRIMARY KEY (id)
)

CREATE TABLE CustomerAddressDetails
(
	id INT IDENTITY(1,1),
	guid UNIQUEIDENTIFIER DEFAULT NEWID(),
	customer_id INT NOT NULL,
	address_name VARCHAR(100) NOT NULL,
	address_1 VARCHAR(200) NOT NULL,
	address_2 VARCHAR(200) NOT NULL,
	city VARCHAR(100) NOT NULL,
	state VARCHAR(100) NOT NULL,
	pincode INT NOT NULL,
	created_date DATETIME DEFAULT GETUTCDATE(),
	updated_date DATETIME NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (customer_id) REFERENCES Customer(id)
)